baseURL = "/"
languageCode = "en-us"
title = "常にいまいち"
theme = "hyde"
googleAnalytics = "UA-155249985-1"

[Params]
author = "ques0942"
description = "blog for something"

[outputs]
home = ["HTML"]
section = ["HTML"]
page = ["HTML"]
