baseURL = "/"
languageCode = "en-us"
title = "常にいまいち"
theme = "hyde"

[Params]
author = "ques0942"
description = "blog for something"

[outputs]
home = ["HTML", "JSON"]
section = ["HTML", "JSON"]
page = ["HTML", "JSON"]
