name: pullrequest from issue

on:
  issues:
    types: [opened, edited, unlabeled]

jobs:
  display:
    runs-on: ubuntu-18.04
    steps:
      - name: display
        run: echo '${{ toJson(github.event) }}'
