name: pullrequest from issue

on:
  issues:
    types: [opened, edited, unlabeled]

env:
  ISSUE_ID: ${{ github.event.issue.id }}
  ISSUE_BODY: ${{ github.event.issue.body }}
  BRANCH: from_issue-${{ github.event.issue.id }}
  MD_PATH: content/posts/${{ github.event.issue.id }}.md

jobs:
  checkout:
    runs-on: ubuntu-18.04
    if: |
      (github.event.action == 'opend' || github.event.action == 'edited')
      && contains(github.event.issue.labels.*.name, 'article')
    steps:
      - uses: actions/checkout@v1
        with:
          ref: source
          submodules: true
      - name: create branch
        run: |
          git checkout -b ${BRANCH}
      - name: dump issue
        run: |
          echo ${ISSUE_BODY} > ${MD_PATH}
          git config --global user.email "github-actions@example.com"
          git config --global user.name "github actions"
          git add ${MD_PATH}
          git commit -m "add post from issue #${ISSUE_ID}"
          git push -u origin ${BRANCH}
