name: pullrequest from issue

on:
  push:
    branches:
      - pullrequest-from-issues
  issues:

jobs:
  display:
    runs-on: ubuntu-18.04
    steps:
      - name: display
        run: echo "${{ toJson(github.event) }}"
