name: pullrequest from issue

on:
  push:
    branches:
      - pullrequest-from-issues
  issues:
    types: [opened, edited]

jobs:
  display:
    runs-on: ubuntu-18.04
    steps:
      - name: display
        run: |
          echo {{github.event}}
